### ISSUE TITLE
Can't see why links aren't working https://kent-maps.online/dickens/mobile-landscapes/

### ISSUE THREAD

**Issue by CarolynOulton** [kent-map/kent#102]
Section 4:2 links not working to:
/dickens/dickens-fort-house/
/dickens/david-copperfield-nuckells-place
/dickens/dickens-dover

**Comment by DigiHum1** [comment]
These links all work now, but the Cooling Church and the graves are sideways

**Comment by clb953** [comment]
No sideways images in latest version of essay file applied in Pull Request:  KMO Landing Page Tidy #1037
