### ISSUE TITLE
https://kent-maps.online/dickens/great-expectations-cooling/

### ISSUE THREAD

**Issue by CarolynOulton** [kent-map/kent#106]
White space

**Comment by DigiHum1** [comment]
Hi Carolyn.  The problem I am having with this article are too many images for the size of article. Also, the images are displaying in various sizes, which is not a problem I have encountered before. I have embedded the images to remove the white space, but when you have a new heading e.g. bibliography, then the image can't cope and inserts white space, so I can't shunt this photo above as there isn't enough text to carry it. The other option is to put the Cooling marshes image next to the quotation at the top.  I either need more wordage or less pictures.  Do you want to have a look at the updated version and see what you think? https://kent-maps.online/dickens/great-expectations-cooling/

**Comment by DigiHum1** [comment]
I got rid of one image as it is used on another page. It's better, but the difference in image sizes doesn't make it perfect

**Comment by CarolynOulton** [comment]
Love it!

Current students, please see https://www.canterbury.ac.uk/current-students for the latest updates.


Prof Carolyn Oulton
THgo4
School of Humanities
Canterbury Christ Church University
Canterbury CT1 1QU

Director International Centre for Victorian Women Writers

Programme Director Creative and Professional Writing

 [cid:79a14b35-2c2d-479f-be34-34538b5a849a]
http://www.worplepress.com/accidental-fruit/



________________________________
