### ISSUE TITLE
https://kent-maps.online/dickens/dickens-biography

### ISSUE THREAD

**Issue by CarolynOulton** [kent-map/kent#15]
3rd para from bottom link to Dickens/ Broadstairs not working. Github link is https://github.com/kent-map/kent/blob/develop/docs/dickens/broadstairs.md

1st line of penultimate para: https://kent-maps.online/dickens-dover not working

Have just tried to edit these in develop branch, but still not working. Message is 404 Page not found. Not sure what I've done this time as took out any extraneous 'bits'.

**Comment by rsnyder** [comment]
Fixed a couple broken links.  At least one had a capitalization error (Broadstairs vs broadstairs)
