### ISSUE TITLE
https://kent-maps.online/dickens/great-expectations-curated-walk

### ISSUE THREAD

**Issue by CarolynOulton** [kent-map/kent#36]
Ship Inn’ not showing as hyperlink in section 1:11 (final para). Need to be careful with this one - on the map should point to the ‘Ship and Lobster’ in Gravesend, not 'The Ship' in Rochester. Address is: Ship and lobster, Mark Ln, Gravesend DA12 2QB
[Characters GE.docx](https://github.com/kent-map/kent/files/5582447/Characters.GE.docx)

**Comment by rsnyder** [comment]
The custom character text has been fixed in development and will be published.  I'm not clear on the second comment.  Is the issue that the Ship Inn reference in the text (in the last essay paragraph) is not hyperlinked or that the Ship and Lobster image for that para is showing the wrong thing?

**Comment by CarolynOulton** [comment]
It's not linked to anything now, which is fine - in the previous version it was - not surprisingly if you haven't been there - linked to the wrong pub.
