### ISSUE TITLE
https://kent-maps.online/dickens/david-copperfield-curated-walk

### ISSUE THREAD

**Issue by CarolynOulton** [kent-map/kent#60]
Section 1:4 link to Rochester goes nowhere.

We never produced a 'Dickens and Rochester' entry per se, so this needs to link to Helena's https://kent-maps.online/develop/dickens/dickens-medway

**Comment by DigiHum1** [comment]
Now amended and ready to go live

**Comment by DigiHum1** [comment]
Still not working - hmmmm
