### ISSUE TITLE
Folkestone Free Library

### ISSUE THREAD

**Issue by CarolynOulton** [kent-map/kent#7]
Missing images cited in text  https://kent-maps.online/19c/19c-folkestone-free-library

**Comment by DigiHum1** [comment]
Hi Carolyn, do you have these images?  Are they in the folder?

**Comment by CarolynOulton** [comment]
First image is at https://www.geograph.org.uk/photo/6441598[](url) The others should be in github but attaching here because I can't find them myself! 
![Kipps in Folkestone Library](https://user-images.githubusercontent.com/57629287/99780446-66d98500-2b0e-11eb-98b9-1565b66260c8.JPG)
![Library indicator](https://user-images.githubusercontent.com/57629287/99780463-6d67fc80-2b0e-11eb-88e9-209a0d210bd6.JPG)

**Comment by DigiHum1** [comment]
I've added them, but will leave this open until you confirm that the page is displaying correctly. I hope Ron can explain what is happening in my browser.  I might try Microsoft Edge and see if that is better

**Comment by CarolynOulton** [comment]
Looking fab - thanks!

**Comment by DigiHum1** [comment]
Folkestone Free Library is not appearing on the live site now and I don't  know why
