### ISSUE TITLE
Thematic articles

### ISSUE THREAD

**Issue by CarolynOulton** [kent-map/kent#87]
Have put Peter V's articles in 20C, but not sure that's the right place for all of them? How do we want to work with geography that covers millennia?

**Comment by DigiHum1** [comment]
We now have quite a few articles by Peter on geography and also quite a few on music from Chris.  We need to have a think about structure - maybe on the front page we have big themes going on e.g

The Kentish Landscape - geography, agriculture, hopping, rural tradition e.g. hoodening
Musical Peregrinations - Chris Price's stuff
The Literary Imagination - where all our literature stuff goes
Kent through Time - Bloody Code, Chatham Dockyward etc

Featured essays could be any theme
Instead of featured authors, we could have "Featured People", Featured Places"

**Comment by CarolynOulton** [comment]
Ooh, like this structure! Why aren't you in bed though? I'm staggering off now under crushing weight of REF paperwork. Is it possible to die of horror in the night after day of battling with aforesaid?

Current students, please see https://www.canterbury.ac.uk/current-students for the latest updates.


Prof Carolyn Oulton
THgo4
School of Humanities
Canterbury Christ Church University
Canterbury CT1 1QU

Director International Centre for Victorian Women Writers

Programme Director Creative and Professional Writing

 [cid:7d009710-c411-455d-96b1-30112313e36c]
http://www.worplepress.com/accidental-fruit/



________________________________

**Comment by DigiHum1** [comment]
It's Match of the Day - I will only get woken up by the thunderous sound of Martin stumbling into the bedroom












[logoEmma]

Michelle Crowther BA, MA, MLib, FHEA

Learning & Research Librarian (Humanities, Languages, Medicine, Health and Social Care)

Library and Learning Resources





Augustine House (AH2.25)| Canterbury Christ Church University | North Holmes Road | Canterbury | Kent | CT1 1QU



michelle.crowther1@canterbury.ac.uk<mailto:michelle.crowther1@canterbury.ac.uk>



+44 (0)1227 922353



Follow us on Twitter @ccculibrary<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fccculibrary&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812647763&sdata=3KE1b4MmbGvXrpNjwjVlQ60ev9ag7PIlpYiXGYj3WBg%3D&reserved=0> @HumLib_cccu <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FHumLib_cccu&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812657761&sdata=nvcz0ng9zDAdcWMnNGoHVGTfRw%2B%2FslbieDgA5d0xlfE%3D&reserved=0>  @HealthLib_cccu<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fhealthlib_cccu%3Flang%3Den&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812657761&sdata=2OL%2BU%2F%2F3rZCAmuF57MJU7EhxzDB0ALyMvSn4qAv%2FUqI%3D&reserved=0>

Website: Staff<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcccu.canterbury.ac.uk%2Flibrary-and-learning-resources%2Flibrary-and-learning-resources.aspx&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812667751&sdata=WUW9pg3gANt%2Fbwj95jYdALlvcUauqgeh5hqzkaa%2BLLE%3D&reserved=0> | Students<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.canterbury.ac.uk%2Fstudents%2Flibrary%2Flibrary.aspx&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812667751&sdata=dCHhdZHLY8%2BTHYtPArZuhS1nSFFxQdo4T4gEk0yimrg%3D&reserved=0> | Blog<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblogs.canterbury.ac.uk%2Flibrary%2F&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812677738&sdata=4S54h%2FFVQ36bkm0UQTl3ZPD0gZWcp1UwYPSGQ%2BdaZXQ%3D&reserved=0>

Any feedback? https://www.canterbury.ac.uk/library/about-us/feedback/library-feedback-form.aspx<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.canterbury.ac.uk%2Flibrary%2Fabout-us%2Ffeedback%2Flibrary-feedback-form.aspx&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812677738&sdata=oRlKKBsAzj949XJx2Ri3KnGPnK4JY7V3NE2og1Dy%2FFs%3D&reserved=0>





Click on the links below for on-line support with study skills, citation & referencing, and research methods

  [cid:image001.png@01D5CD15.1FD57DB0] <https://eur01.safelinks.protection.outlook.com/?url=bit.ly%2FBBSLDRS&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812687731&sdata=mOJ8ieMF1yVjbdETIxZ8KSnQJ%2FOHhvXropKdqi5iSE4%3D&reserved=0>  [cid:9b1a5390-1754-4fd4-a9a8-4490bab749ae] <https://ulms.ent.sirsidynix.net.uk/client/en_GB/CCCU> [cid:4f2698dd-de9e-4711-9b33-2bd6f577a291] <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.skills4studycampus.com%2Fmain%2F&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812687731&sdata=hZLjjMr1fPwviw7MoENakHppMCUHuBVrAtgglkNsQ9A%3D&reserved=0>   [cid:62eea214-2c7b-490c-9796-db9ee964f608] <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.citethemrightonline.com%2F&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812697724&sdata=hfV%2BKv8%2BGZn0bNMn4E957iFNA8TzNWXfs6hj%2FYjMBaA%3D&reserved=0>   [cid:67fca023-2766-4be1-8d00-4167eb19601d] <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmethods.sagepub.com%2F&data=02%7C01%7Cmichelle.crowther1%40canterbury.ac.uk%7Ce36d753f6a24405c9ffa08d7aa600cfe%7C0320b2da22dd4dab8c216e644ba14f13%7C0%7C0%7C637165201812697724&sdata=HAT8bZG8m3VGpDXafQmsXB0vuohpTdFgdYQTcNEVZuc%3D&reserved=0>

________________________________

**Comment by CarolynOulton** [comment]
Ok now I REALLY won't sleep. I loathe football.

Current students, please see https://www.canterbury.ac.uk/current-students for the latest updates.


Prof Carolyn Oulton
THgo4
School of Humanities
Canterbury Christ Church University
Canterbury CT1 1QU

Director International Centre for Victorian Women Writers

Programme Director Creative and Professional Writing

 [cid:97a709bc-b856-4fab-802a-c44a86992d66]
http://www.worplepress.com/accidental-fruit/



________________________________
