### ISSUE TITLE
16th century

### ISSUE THREAD

**Issue by DigiHum1** [kent-map/kent#961]
16th Century:
[The Maid of Kent: Elizabeth Barton](https://www.kent-maps.online/16c/16c-barton-biography/#fnref:ref4)
•	Section 5 is just a picture link.
•	Section 6 has a picture link visible at the end.
•	Section 8’s picture description has a typo: (UJames…)
•	Section 9’s picture description says Unknown Author twice.
•	Reference list: Watt and United Kingdom are not in alphabetical order.

**Comment by clb953** [comment]
Fixed as part of Pull Request: Ad hoc & open issue fixes https://github.com/kent-map/kent/pull/1014
