### ISSUE TITLE
Spanish Armada

### ISSUE THREAD

**Issue by DigiHum1** [kent-map/kent#962]
[The Spanish Armada and Kent](https://www.kent-maps.online/16c/16c-spanish-armada/)
•	Section 3: The first speech mark is facing the wrong direction.
•	Section 3: The colon has an extra space before it.
•	Section 6: space between speech mark and hyphen missing (‘hellburners’-…)

**Comment by clb953** [comment]
Fixed

**Comment by clb953** [comment]
Fixed with Pull Request: Fixed Open Issues (x4) #1046

**Comment by DigiHum1** [comment]
[like]  Michelle Crowther reacted to your message:
________________________________
